name: Build and test main

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/node_modules
          key: cache-${{ hashFiles('**/package-lock.json') }}

      - name: Install and build
        run: |
          npm install
          npm run build

      - name: Test with Jest
        run: npm run test
      
      - name: Lint with ESLint
        run: npm run lint